server:
  port: 7550

spring:
  application:
    name: gate-way
  resources:
    static-locations: classpath:/static
  datasource:
    url:  jdbc:oracle:thin:@//localhost:1521/ORCL
    type: org.apache.tomcat.jdbc.pool.DataSource
    password: root
    username: system
    tomcat:
      validation-query: select 1 from dual


eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:7537/eureka/

shiro:
  filter:
  - /css/**
  - /js/**
  - favicon.ico
  #- /**/*.html
  logout:
    /logout
  authc:
    /**
  loginUrl:
    http://localhost:8080/login.html
  loginUri:
    /comm/login
  successUrl:
    http://localhost:8080/index.html
  errorUrl:
    /403

#zuul:
  #routes:
    #customers: /customers/**
    #path: /user/**
logging:
  level:
    com.cloud: debug

mybatis:
  mapper-locations: classpath:com/cloud/**/*.xml

