server:
  port: 7550

spring:
  application:
    name: gate-way

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:7537/eureka/

zuul:
  routes:
    customers: /customers/**
      #path: /user/**
logging:
  level:
    com.cloud: debug
